server:
  port: 8088
spring:
  r2dbc:
    url: r2dbc:postgresql://172.17.0.2/cats
    username: dev
    password: ${DB_PASS}
    name: cats
  application:
    name: jt-cats
eureka:
  instance:
    instance-id: welt-cats-${spring.application.name}